<Project>

  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Package metadata -->
    <Authors>magna-nz</Authors>
    <Company>magna-nz</Company>
    <Product>RedStream</Product>
    <Copyright>Copyright © 2026 magna-nz</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/magna-nz/RedStream</PackageProjectUrl>
    <RepositoryUrl>https://github.com/magna-nz/RedStream.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>redis;streams;message-queue;stackexchange.redis;opentelemetry;dotnet;aspnetcore</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <!-- Version -->
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
