<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RedStream\RedStream.csproj" />
    <ProjectReference Include="..\..\src\RedStream.Testing\RedStream.Testing.csproj" />
  </ItemGroup>

</Project>
